name: Build and Commit WASM

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'wasm/**'
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-wasm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build WASM package
        run: |
          cd russell_engine
          wasm-pack build --target web --out-dir pkg --release

      - name: Prepare wasm directory
        run: |
          mkdir -p wasm
          cp -r russell_engine/pkg/* wasm/

      - name: Commit and push WASM files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci: update wasm build"
          file_pattern: "wasm/**"
